language: node_js
node_js: node
os:
  - linux
  - osx
cache:
  directories:
  - node_modules
before_deploy:
  - npm install -g electron-forge@3.0.5
  - electron-forge make
deploy:
  provider: releases
  file_glob: true
  file: out/make/*
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
