language: node_js
node_js: node
os:
  - linux
  - osx
cache:
  directories:
  - node_modules
before_deploy:
  - npm run make
deploy:
  provider: releases
  api_key:
    secure: TtJKGLRP2I8gZXgef0TS0CClNbDzQdHMBhmZyCrMCkU/sVGLfqmEm1r79vMAFS+7wObRbKya84BWUdzfX295FC/yyrBYJyjsd9Dd0srTKM4HU282AZsjlHlXU3Xx+wNlSoJCNt6SqnxMAOnQHjvJe1bO4VCa1u/Njb9KjxyRJdzQ6g9o/EL/AUBEynNQwQZAygQqKTEooerIqAc+QHjqjB6oOQjm7yHb3X4BsCPfqXhP87wnCzIuS9NLRb/obr2UjiOejLoxoReHfyAQoEAKLcHADKNQFbbK8sWekmg+8fxLv4ac1JhUcSZg6E9gwyrFN9P23jX0cl7bCxfZfYBMTAG3pPl98k3SVDCPsu11D+WmFI2wtQXY2GjUOschbQrekeU7iiGv53+T6YCiNZSsryMND1D8aXnyhtNgoRVttWlGyZKqfxF8olw/y0chGKjcs4gvNhlQPwqCJfmuhpJ5DSt3ALHY7opyxXuxGQzEk+wRj4i4+DOWS2LHYLnUXJVSOKrWV95iEIiEDSAy//RnZGS8rzmBl5dW6IPddKdYjQig/9+xUkbX9AzQ3Cjg4eYdN2SgbEOMZ7gqIib/82QvE4ickYzbVgSEfhCFreL3F3td/gVHs26awf9Uhrn2N8ogzaSWr8zqo7EJ04KqNQ1s1l6C5lnopqMpM4DigBS6UiA=
  file_glob: true
  file: out/make/*
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
