language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: releases
  overwrite: true
  file_glob: true
  api_key:
    secure: UYaUne1VypL50wYtlGAxuupmPpDZ8fLre0/s8aMbuvDmoIKpce1WZptBnu2l0/B8O5FyXUDMXyGwW5bZNYG+NlPHz244XvShNggbr8A8gv9eMqoiDXT0HlOmSufnOeWRcA0p90sreq1wwxbE7AsiRD8GZEXS0R5/y+8Gz5yQJ4hjLnEtXt7RSVMCwhKVIYs2P8FmK4ASfdb6FGyhXnFZdmpvgbT1tU9m8bEhu0ZCuijBW8rZfgE17uUFOcRYl3ZBcadyUuqB4BSVxrG+Ggewjw7D64m5iIyPd+bGc7Iqfyi8NhsRLiPtpbeplDlpfgyqje/rCQU05/mHE1rQkHj0qWpcjxjsbEXUPmSloe/HH2aXp87cDrvyERqowcfjVRLGALkGTdw0IWyuSRZdZQIy3jydAqZ3xxJJpRVIt0ieBxBldFT1AhkOb8+AzxrYgTluoGWMDlNTgToI2+mVgkkdQ9vTm0mYpL7/A0kwFhp90x+kCqVIMWcq9MgjtKtQuGsifrGP1VPWfmJ2esPm5CgnNzGloPz+fkWDiT9khmoDeV4XArl/lcY+DHjzSChx0/N9xpoZWY7eqF7A3TjtAh1+XJnQPNeNUy+smEQMhzGUbxITX6wQ1UUBWy/nM3CCcjFwq2dOKtNO5gNd7pIL8FRCKb6gn4+kMnhCJVOf7JkcuIg=
  file: out/make/*
  skip_cleanup: true
  on:
    tags: true
