version: "{build}"
build: off
platform:                           # Platforms to test/build on
  - x86
environment:
  nodejs_version: "8"               # Test against the latest version of this Node.js version
install:                            # Install scripts. (runs after repo cloning)
  - ps: Install-Product node $env:nodejs_version # Get the latest stable version of Node.js or io.js
  - npm install                     # install modules
  - npm install -g electron-forge@3.0.5 # install electron-forge cli
cache:
  - node_modules
skip_non_tags: true                 # Only build tags (we use travis-ci for tests)
test_script:
  - node --version
  - npm --version
  - npm test                        # run tests
after_test:                         # run build after tests
  - npm run make                    # Script to package/compile
artifacts:
  - path: 'out\make\**\*.exe'            # upload all files in ./out/make
    name: exe
# Deploy settings
deploy:
  release: $(appveyor_repo_tag_name)
  description: 'Release description'
  provider: GitHub
  artifacts: exe
  draft: true
  prerelease: true
  auth_token:                      # provide the github personal access token in appveyor settings and view the export yml
    secure: Xjyk9DTGg6aLGwZVfuQVAKy5flL5mY0Z2xxg1ZNtA4nEAUxw7UBOHJEmkq/J+IJE
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
